@startuml

object "Instructor1: Instructor" as Instructor1 {
    firstName = "Nima"
    lastName = "Davarpanah"
    officeNumber = "3-2636"
}

object "Textbook1: Textbook" as Textbook1 {
    title = "Clean Code"
    author = "Robert C. Martin"
    publisher = "Prentice Hall"
}

object "Course1: Course" as course1 {
    courseName = "Software Engineering"
    instructor = Instructor1
    textbook = Textbook1
}

course1 o-- Instructor1
course1 o-- Textbook1
@enduml
